config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  resources :spells, only: [:index, :show]
  resources :creatures, only: [:index, :show]
  resources :special_abilities, only: [:index, :show]
  resources :actions, only: [:index, :show]
  resources :legendary_actions, only: [:index, :show]
end

app/models/action.rb
class Action < ApplicationRecord
	belongs_to :creature
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/creature.rb
class Creature < ApplicationRecord
	has_many :special_abilities
	has_many :actions
	has_many :legendary_actions

	def has_skills?
		return true if self.athletics || self.acrobatics || self.stealth || self.arcana || self.history || self.investigation || self.nature || self.religion || self.insight || self.medicine || self.perception || self.survival || self.deception || self.intimidation || self.performance || self.persuasion
	end

	def has_saving_throws?
		return true if self.constitution_save || self.intelligence_save || self.wisdom_save
	end

	def has_damage_modifiers?
		return true if self.damage_vulnerabilities.length > 0 || self.damage_resistances.length > 0 || self.damage_immunities.length > 0 || self.condition_immunities.length > 0
	end
end

app/models/legendary_action.rb
class LegendaryAction < ApplicationRecord
	belongs_to :creature
end

app/models/special_ability.rb
class SpecialAbility < ApplicationRecord
	belongs_to :creature
end

app/models/spell.rb
class Spell < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/creatures_controller.rb
class CreaturesController < ApplicationController

	def index
		@creatures = Creature.all
	end

	def show
		@creature = Creature.find(params[:id])
	end
	
end

app/controllers/spells_controller.rb
class SpellsController < ApplicationController

	def index
		@spells = Spell.all
	end

	def show
		@spell = Spell.find(params[:id])
	end

	private

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/creatures/actions/_show.html.erb
<!-- show action partial -->
<li>
	<div class="collapsible-header"><%= action.name %></div>
	<div class="collapsible-body">
		<p><%= action.desc %></p>
		<table>
			<% if action.attack_bonus > 0 %>
				<tr>
					<td>Attack Bonus</td>
					<td><%= action.attack_bonus %></td>
				</tr>
			<% end %>
			<% if action.damage_dice %>
				<tr>
					<td>Damage Dice</td>
					<td><%= action.damage_dice %></td>
				</tr>
			<% end %>
			<% if action.damage_bonus %>
				<tr>
					<td>Damage Bonus</td>
					<td><%= action.damage_bonus %></td>
				</tr>
			<% end %>
		</table>
	</div>
</li>

app/views/creatures/index.html.erb
<!-- show all creatures -->
<h1>All Creatures</h1>
<% @creatures.each do |creature| %>
	<p><%= link_to "#{creature.name}", creature_path(creature.id) %></p>
<% end %>

app/views/creatures/legendary_actions/_show.html.erb
<!-- show legendary action partial -->
<li>
<div class="collapsible-header"><%= legendary_action.name %></div>
	<div class="collapsible-body"><%= legendary_action.desc %>
		<table>
			<% if legendary_action.attack_bonus > 0 %>
				<tr>
					<td>Attack Bonus</td>
					<td><%= legendary_action.attack_bonus %></td>
				</tr>
			<% end %>
			<% if legendary_action.attack_bonus > 0 %>
				<tr>
					<td>Damage Dice</td>
					<td><%= legendary_action.attack_bonus %></td>
				</tr>
			<% end %>
		</table>
	</div>
</li>

app/views/creatures/show.html.erb
<!-- show creature -->
<h1><%= @creature.name %></h1>
<div class="row">
	<div class="col s5">
		<p>General Information</p>
		<table class="bordered">
			<tr>
				<td>Type</td>
				<td><%= @creature.creature_type %></td>
			</td>
			<% if @creature.subtype.length > 0 %>
				<tr>
					<td>Subtype</td>
					<td><%= @creature.subtype %>
				</td>
			<% end %>
			<% if @creature.alignment %>
				<tr>
					<td>Alignment</td>
					<td><%= @creature.alignment %></td>
				</tr>
			<% end %>
			<tr>
				<td>Armor Class</td>
				<td><%= @creature.armor_class %></td>
			</tr>
			<tr>
				<td>Hit Points</td>
				<td><%= @creature.hit_points %></td>
			</tr>
			<tr>
				<td>Hit Dice</td>
				<td><%= @creature.hit_dice %></td>
			</tr>
			<tr>
				<td>Speed</td>
				<td><%= @creature.speed %></td>
			</tr>
		</table>
			<!-- Ability Scores -->
		<p>Ability Scores</p>
		<table class="centered bordered">
			<thead>
				<tr>
					<th>STR</th>
					<th>DEX</th>
					<th>CON</th>
					<th>INT</th>
					<th>WIS</th>
					<th>CHR</th>
				</tr>
			</thead>
			<tbody>
				<tr>
					<td><%= @creature.strength %></td>
					<td><%= @creature.dexterity %></td>
					<td><%= @creature.constitution %></td>
					<td><%= @creature.intelligence %></td>
					<td><%= @creature.wisdom %></td>
					<td><%= @creature.charisma %></td>
				</tr>
			</tbody>
		</table>
			<!-- Saving Throws -->
			<% if @creature.has_saving_throws? %>
				<p>Saving Throws</p>
				<th colspan="2">Saving Throws</th>
				<% if @creature.constitution_save %>
					<tr>
						<td>Constitution Save</td>
						<td><%= @creature.constitution_save %></td>
					</tr>
				<% end %>
				<% if @creature.intelligence_save %>
					<tr>
						<td>Intelligence Save</td>
						<td><%= @creature.intelligence_save %></td>
					</tr>
				<% end %>
				<% if @creature.wisdom_save %>
					<tr>
						<td>Wisdom Save</td>
						<td><%= @creature.wisdom_save %></td>
					</tr>
				<% end %>
			<% end %>
			<!-- CREATURE SKILLS -->
			<!-- Only display Skills section if Creature has any -->
			<!-- Only display individual Skills if Creature has that skill -->
			<% if @creature.has_skills? %>
				<th colspan="2">Skills</th>
				<% if @creature.athletics %>
					<tr>
						<td>Athletics</td>
						<td><%= @creature.athletics %></td>
					</tr>
				<% end %>
				<% if @creature.acrobatics %>
					<tr>
						<td>Acrobatics</td>
						<td><%= @creature.acrobatics %></td>
					</tr>
				<% end %>
				<% if @creature.stealth %>
					<tr>
						<td>Stealth</td>
						<td><%= @creature.stealth %></td>
					</tr>
				<% end %>
				<% if @creature.arcana %>
					<tr>
						<td>Arcana</td>
						<td><%= @creature.arcana %></td>
					</tr>
				<% end %>
				<% if @creature.history %>
					<tr>
						<td>History</td>
						<td><%= @creature.history %></td>
					</tr>
				<% end %>
				<% if @creature.investigation %>
					<tr>
						<td>Investigation</td>
						<td><%= @creature.investigation %></td>
					</tr>
				<% end %>
				<% if @creature.nature %>
					<tr>
						<td>Nature</td>
						<td><%= @creature.nature %></td>
					</tr>
				<% end %>
				<% if @creature.religion %>
					<tr>
						<td>Religion</td>
						<td><%= @creature.religion %></td>
					</tr>
				<% end %>
				<% if @creature.insight %>
					<tr>
						<td>Insight</td>
						<td><%= @creature.insight %></td>
					</tr>
				<% end %>
				<% if @creature.medicine %>
					<tr>
						<td>Medicine</td>
						<td><%= @creature.medicine %></td>
					</tr>
				<% end %>
				<% if @creature.perception %>
					<tr>
						<td>Perception</td>
						<td><%= @creature.perception %></td>
					</tr>
				<% end %>
				<% if @creature.survival %>
					<tr>
						<td>Survival</td>
						<td><%= @creature.survival %></td>
					</tr>
				<% end %>
				<% if @creature.deception %>
					<tr>
						<td>Deception</td>
						<td><%= @creature.deception %></td>
					</tr>
				<% end %>
				<% if @creature.intimidation %>
					<tr>
						<td>Intimidation</td>
						<td><%= @creature.intimidation %></td>
					</tr>
				<% end %>
				<% if @creature.performance %>
					<tr>
						<td>Performance</td>
						<td><%= @creature.performance %></td>
					</tr>
				<% end %>
				<% if @creature.persuasion %>
					<tr>
						<td>Persuasion</td>
						<td><%= @creature.persuasion %></td>
					</tr>
				<% end %>
			<% end %>
			<% if @creature.has_damage_modifiers? %>
				<th colspan="2">Damage Modifiers</th>
				<% if @creature.damage_vulnerabilities.length > 0 %>
					<tr>
						<td>Damage Vulnerabilities</td>
						<td><%= @creature.damage_vulnerabilities %></td>
					</tr>
				<% end %>
				<% if @creature.damage_resistances.length > 0 %>
					<tr>
						<td>Damage Resistances</td>
						<td><%= @creature.damage_resistances %></td>
					</tr>
				<% end %>
				<% if @creature.damage_immunities.length > 0 %>
					<tr>
						<td>Damage Immunities</td>
						<td><%= @creature.damage_immunities %></td>
					</tr>
				<% end %>
				<% if @creature.condition_immunities.length > 0 %>
					<tr>
						<td>Condition Immunities</td>
						<td><%= @creature.condition_immunities %></td>
					</tr>
				<% end %>
			<% end %>
			<th colspan="2">Miscellaneous</th>
			<tr>
				<td>Senses</td>
				<td><%= @creature.senses %></td>
			</tr>
			<% if @creature.languages.length > 0 %>
				<tr>
					<td>Languages</td>
					<td><%= @creature.languages %></td>
				</tr>
			<% end %>
			<tr>
				<td>Challenge Rating</td>
				<td><%= @creature.challenge_rating %></td>
			</tr>
		</table>
	</div>

	<div class="col s7">
		<% if @creature.special_abilities.length > 0 %>
			<h4>Special Abilities</h4>
		  <ul class="collapsible" data-collapsible="expandable">
			<% @creature.special_abilities.each do |special_ability| %>
				<%= render partial: "creatures/special_abilities/show", locals: { special_ability: special_ability }, layout: false %>
			<% end %>
			</ul>
		<% end %>
	 
		<% if @creature.actions.length > 0 %>
			<h4>Actions</h4>
		  <ul class="collapsible" data-collapsible="expandable">
			<% @creature.actions.each do |action| %>
				<%= render partial: "creatures/actions/show", locals: { action: action }, layout: false %>
			<% end %>
			</ul>
		<% end %>

		<% if @creature.legendary_actions.length > 0 %>
			<h4>Legendary Actions</h4>
		  <ul class="collapsible" data-collapsible="expandable">
			<% @creature.legendary_actions.each do |legendary_action| %>
				<%= render partial: "creatures/legendary_actions/show", locals: { legendary_action: legendary_action }, layout: false %>
			<% end %>
			</ul>
		<% end %>

	</div>
</div>

<div class="center-align">
	<% unless @creature.id == 1 %>
		<a class="waves-effect waves-light btn" href=<%= "/creatures/#{@creature.id - 1}" %>><i class="material-icons left">skip_previous</i>Prev Creature</a>
	<% end %>

	<a class="waves-effect waves-light btn" href="/creatures">Home</a>

	<% unless @creature.id == Creature.all.length %>
		<a class="waves-effect waves-light btn" href=<%= "/creatures/#{@creature.id + 1}" %>><i class="material-icons right">skip_next</i>Next Creature</a>
	<% end %>
</div>
		

app/views/creatures/special_abilities/_show.html.erb
<!-- show special ability partial -->
<li>
	<div class="collapsible-header"><%= special_ability.name %></div>
	<div class="collapsible-body">
		<p><%= special_ability.desc %></p>
		<table>
			<% if special_ability.attack_bonus > 0 %>
				<tr>
					<td>Attack Bonus</td>
					<td><%= special_ability.attack_bonus %></td>
				</tr>
			<% end %>
			<% if special_ability.damage_dice %>
				<tr>
					<td>Damage Dice</td>
					<td><%= special_ability.damage_dice %></td>
				</tr>
			<% end %>
			<% if special_ability.damage_bonus %>
				<tr>
					<td>Damage Bonus</td>
					<td><%= special_ability.damage_bonus %></td>
				</tr>
			<% end %>
		</table>
	</div>
</li>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>DungeonsAndDragons5eTools</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all' %>
    <%= javascript_include_tag 'application' %>
    <!-- include general icons -->
    <link href="https://fonts.googleapis.com/icon?family=Material+Icons" rel="stylesheet">
  </head>

  <body>
  	<div class="container">
	    <%= yield %>
	  </div>
  </body>
</html>

app/views/spells/index.html.erb
<!-- show all spells -->
<h1>All Spells</h1>
<% @spells.each do |spell| %>
	<p><%= link_to "#{spell.name}", spell_path(spell.id) %></p>
<% end %>

app/views/spells/show.html.erb
<!-- show spell -->
<h1><%= @spell.name %></h1>
<%= @spell.desc.html_safe %>
<%= @spell.higher_level.html_safe if @spell.higher_level %>
<table>
	<tr>
		<td>Reference Page</td>
		<td><%= @spell.page.upcase %></td>
	</tr>
	<tr>
		<td>Range</td>
		<td><%= @spell.range %></td>
	</tr>
	<tr>
		<td>Components</td>
		<td><%= @spell.components %></td>
	</tr>
	<% if @spell.material %>
		<tr>
			<td>Material</td>
			<td><%= @spell.material %></td>
		</tr>
	<% end %>
	<tr>
		<td>Ritual</td>
		<td><%= @spell.ritual %></td>
	</tr>
	<tr>
		<td>Duration</td>
		<td><%= @spell.duration %></td>
	</tr>
	<tr>
		<td>Concentration</td>
		<td><%= @spell.concentration %></td>
	</tr>
	<tr>
		<td>Casting Time</td>
		<td><%= @spell.casting_time %></td>
	</tr>
	<tr>
		<td>Level</td>
		<td><%= @spell.level %></td>
	</tr>
	<tr>
		<td>School</td>
		<td><%= @spell.school %></td>
	</tr>
	<tr>
		<td>Spell Class</td>
		<td><%= @spell.spell_class %></td>
	</tr>
	<% if @spell.archetype %>
		<tr>
			<td>Archetype</td>
			<td><%= @spell.archetype.html_safe %></td>
		</tr>
	<% end %>
	<% if @spell.circles %>
		<tr>
			<td>Circles</td>
			<td><%= @spell.circles %></td>
		</tr>
	<% end %>
	<% if @spell.oaths %>
		<tr>
			<td>Oaths</td>
			<td><%= @spell.oaths %></td>
		</tr>
	<% end %>
	<% if @spell.domains %>
		<tr>
			<td>Domains</td>
			<td><%= @spell.domains %></td>
		</tr>
	<% end %>
	<% if @spell.patrons %>
		<tr>
			<td>Patrons</td>
			<td><%= @spell.patrons %></td>
		</tr>
	<% end %>
</table>
<% unless @spell.id == 1 %>
	<%= link_to 'Previous Spell', spell_path(@spell.id - 1) %>
<% end %>
<%= link_to 'Home', spells_path %>
<% unless @spell.id == Spell.all.length %>
	<%= link_to 'Next Spell', spell_path(@spell.id + 1) %>
<% end %>